<?php
/**
 * AnalyticsFlowOutcome
 *
 * PHP version 5
 *
 * @category Class
 * @package  PureCloudPlatform\Client\V2
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PureCloud Platform API
 *
 * With the PureCloud Platform API, you can control all aspects of your PureCloud environment. With the APIs you can access the system configuration, manage conversations and more.
 *
 * OpenAPI spec version: v2
 * Contact: DeveloperEvangelists@genesys.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.9
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace PureCloudPlatform\Client\V2\Model;

use \ArrayAccess;
use \PureCloudPlatform\Client\V2\ObjectSerializer;

/**
 * AnalyticsFlowOutcome Class Doc Comment
 *
 * @category Class
 * @package  PureCloudPlatform\Client\V2
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AnalyticsFlowOutcome implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'AnalyticsFlowOutcome';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'flowOutcomeId' => 'string',
        'flowOutcomeValue' => 'string',
        'flowOutcome' => 'string',
        'flowOutcomeStartTimestamp' => '\DateTime',
        'flowOutcomeEndTimestamp' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'flowOutcomeId' => null,
        'flowOutcomeValue' => null,
        'flowOutcome' => null,
        'flowOutcomeStartTimestamp' => 'date-time',
        'flowOutcomeEndTimestamp' => 'date-time'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'flowOutcomeId' => 'flowOutcomeId',
        'flowOutcomeValue' => 'flowOutcomeValue',
        'flowOutcome' => 'flowOutcome',
        'flowOutcomeStartTimestamp' => 'flowOutcomeStartTimestamp',
        'flowOutcomeEndTimestamp' => 'flowOutcomeEndTimestamp'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'flowOutcomeId' => 'setFlowOutcomeId',
        'flowOutcomeValue' => 'setFlowOutcomeValue',
        'flowOutcome' => 'setFlowOutcome',
        'flowOutcomeStartTimestamp' => 'setFlowOutcomeStartTimestamp',
        'flowOutcomeEndTimestamp' => 'setFlowOutcomeEndTimestamp'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'flowOutcomeId' => 'getFlowOutcomeId',
        'flowOutcomeValue' => 'getFlowOutcomeValue',
        'flowOutcome' => 'getFlowOutcome',
        'flowOutcomeStartTimestamp' => 'getFlowOutcomeStartTimestamp',
        'flowOutcomeEndTimestamp' => 'getFlowOutcomeEndTimestamp'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['flowOutcomeId'] = isset($data['flowOutcomeId']) ? $data['flowOutcomeId'] : null;
        $this->container['flowOutcomeValue'] = isset($data['flowOutcomeValue']) ? $data['flowOutcomeValue'] : null;
        $this->container['flowOutcome'] = isset($data['flowOutcome']) ? $data['flowOutcome'] : null;
        $this->container['flowOutcomeStartTimestamp'] = isset($data['flowOutcomeStartTimestamp']) ? $data['flowOutcomeStartTimestamp'] : null;
        $this->container['flowOutcomeEndTimestamp'] = isset($data['flowOutcomeEndTimestamp']) ? $data['flowOutcomeEndTimestamp'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets flowOutcomeId
     *
     * @return string
     */
    public function getFlowOutcomeId()
    {
        return $this->container['flowOutcomeId'];
    }

    /**
     * Sets flowOutcomeId
     *
     * @param string $flowOutcomeId Unique identifiers of a flow outcome
     *
     * @return $this
     */
    public function setFlowOutcomeId($flowOutcomeId)
    {
        $this->container['flowOutcomeId'] = $flowOutcomeId;

        return $this;
    }

    /**
     * Gets flowOutcomeValue
     *
     * @return string
     */
    public function getFlowOutcomeValue()
    {
        return $this->container['flowOutcomeValue'];
    }

    /**
     * Sets flowOutcomeValue
     *
     * @param string $flowOutcomeValue Flow outcome value, e.g. SUCCESS
     *
     * @return $this
     */
    public function setFlowOutcomeValue($flowOutcomeValue)
    {
        $this->container['flowOutcomeValue'] = $flowOutcomeValue;

        return $this;
    }

    /**
     * Gets flowOutcome
     *
     * @return string
     */
    public function getFlowOutcome()
    {
        return $this->container['flowOutcome'];
    }

    /**
     * Sets flowOutcome
     *
     * @param string $flowOutcome Colon-separated combinations of unique flow outcome identifier and value
     *
     * @return $this
     */
    public function setFlowOutcome($flowOutcome)
    {
        $this->container['flowOutcome'] = $flowOutcome;

        return $this;
    }

    /**
     * Gets flowOutcomeStartTimestamp
     *
     * @return \DateTime
     */
    public function getFlowOutcomeStartTimestamp()
    {
        return $this->container['flowOutcomeStartTimestamp'];
    }

    /**
     * Sets flowOutcomeStartTimestamp
     *
     * @param \DateTime $flowOutcomeStartTimestamp Date/time the outcome started. Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss.SSSZ
     *
     * @return $this
     */
    public function setFlowOutcomeStartTimestamp($flowOutcomeStartTimestamp)
    {
        $this->container['flowOutcomeStartTimestamp'] = $flowOutcomeStartTimestamp;

        return $this;
    }

    /**
     * Gets flowOutcomeEndTimestamp
     *
     * @return \DateTime
     */
    public function getFlowOutcomeEndTimestamp()
    {
        return $this->container['flowOutcomeEndTimestamp'];
    }

    /**
     * Sets flowOutcomeEndTimestamp
     *
     * @param \DateTime $flowOutcomeEndTimestamp Date/time the outcome ended. Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss.SSSZ
     *
     * @return $this
     */
    public function setFlowOutcomeEndTimestamp($flowOutcomeEndTimestamp)
    {
        $this->container['flowOutcomeEndTimestamp'] = $flowOutcomeEndTimestamp;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


