<?php
/**
 * CallHistoryConversationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  PureCloudPlatform\Client\V2
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PureCloud Platform API
 *
 * With the PureCloud Platform API, you can control all aspects of your PureCloud environment. With the APIs you can access the system configuration, manage conversations and more.
 *
 * OpenAPI spec version: v2
 * Contact: DeveloperEvangelists@genesys.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.9
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace PureCloudPlatform\Client\V2;

/**
 * CallHistoryConversationTest Class Doc Comment
 *
 * @category    Class
 * @description CallHistoryConversation
 * @package     PureCloudPlatform\Client\V2
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CallHistoryConversationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CallHistoryConversation"
     */
    public function testCallHistoryConversation()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "participants"
     */
    public function testPropertyParticipants()
    {
    }

    /**
     * Test attribute "direction"
     */
    public function testPropertyDirection()
    {
    }

    /**
     * Test attribute "wentToVoicemail"
     */
    public function testPropertyWentToVoicemail()
    {
    }

    /**
     * Test attribute "missedCall"
     */
    public function testPropertyMissedCall()
    {
    }

    /**
     * Test attribute "startTime"
     */
    public function testPropertyStartTime()
    {
    }

    /**
     * Test attribute "wasConference"
     */
    public function testPropertyWasConference()
    {
    }

    /**
     * Test attribute "wasCallback"
     */
    public function testPropertyWasCallback()
    {
    }

    /**
     * Test attribute "hadScreenShare"
     */
    public function testPropertyHadScreenShare()
    {
    }

    /**
     * Test attribute "hadCobrowse"
     */
    public function testPropertyHadCobrowse()
    {
    }

    /**
     * Test attribute "wasOutboundCampaign"
     */
    public function testPropertyWasOutboundCampaign()
    {
    }

    /**
     * Test attribute "selfUri"
     */
    public function testPropertySelfUri()
    {
    }
}
