<?php
/**
 * CampaignInteractionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  PureCloudPlatform\Client\V2
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PureCloud Platform API
 *
 * With the PureCloud Platform API, you can control all aspects of your PureCloud environment. With the APIs you can access the system configuration, manage conversations and more.
 *
 * OpenAPI spec version: v2
 * Contact: DeveloperEvangelists@genesys.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.9
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace PureCloudPlatform\Client\V2;

/**
 * CampaignInteractionTest Class Doc Comment
 *
 * @category    Class
 * @description CampaignInteraction
 * @package     PureCloudPlatform\Client\V2
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CampaignInteractionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CampaignInteraction"
     */
    public function testCampaignInteraction()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "campaign"
     */
    public function testPropertyCampaign()
    {
    }

    /**
     * Test attribute "agent"
     */
    public function testPropertyAgent()
    {
    }

    /**
     * Test attribute "contact"
     */
    public function testPropertyContact()
    {
    }

    /**
     * Test attribute "destinationAddress"
     */
    public function testPropertyDestinationAddress()
    {
    }

    /**
     * Test attribute "activePreviewCall"
     */
    public function testPropertyActivePreviewCall()
    {
    }

    /**
     * Test attribute "lastActivePreviewWrapupTime"
     */
    public function testPropertyLastActivePreviewWrapupTime()
    {
    }

    /**
     * Test attribute "creationTime"
     */
    public function testPropertyCreationTime()
    {
    }

    /**
     * Test attribute "callPlacedTime"
     */
    public function testPropertyCallPlacedTime()
    {
    }

    /**
     * Test attribute "callRoutedTime"
     */
    public function testPropertyCallRoutedTime()
    {
    }

    /**
     * Test attribute "previewConnectedTime"
     */
    public function testPropertyPreviewConnectedTime()
    {
    }

    /**
     * Test attribute "queue"
     */
    public function testPropertyQueue()
    {
    }

    /**
     * Test attribute "script"
     */
    public function testPropertyScript()
    {
    }

    /**
     * Test attribute "disposition"
     */
    public function testPropertyDisposition()
    {
    }

    /**
     * Test attribute "callerName"
     */
    public function testPropertyCallerName()
    {
    }

    /**
     * Test attribute "callerAddress"
     */
    public function testPropertyCallerAddress()
    {
    }

    /**
     * Test attribute "previewPopDeliveredTime"
     */
    public function testPropertyPreviewPopDeliveredTime()
    {
    }

    /**
     * Test attribute "conversation"
     */
    public function testPropertyConversation()
    {
    }

    /**
     * Test attribute "dialerSystemParticipantId"
     */
    public function testPropertyDialerSystemParticipantId()
    {
    }

    /**
     * Test attribute "dialingMode"
     */
    public function testPropertyDialingMode()
    {
    }

    /**
     * Test attribute "skills"
     */
    public function testPropertySkills()
    {
    }
}
