<?php
/**
 * EdgeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  PureCloudPlatform\Client\V2
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PureCloud Platform API
 *
 * With the PureCloud Platform API, you can control all aspects of your PureCloud environment. With the APIs you can access the system configuration, manage conversations and more.
 *
 * OpenAPI spec version: v2
 * Contact: DeveloperEvangelists@genesys.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.9
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace PureCloudPlatform\Client\V2;

/**
 * EdgeTest Class Doc Comment
 *
 * @category    Class
 * @description Edge
 * @package     PureCloudPlatform\Client\V2
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EdgeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Edge"
     */
    public function testEdge()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "version"
     */
    public function testPropertyVersion()
    {
    }

    /**
     * Test attribute "dateCreated"
     */
    public function testPropertyDateCreated()
    {
    }

    /**
     * Test attribute "dateModified"
     */
    public function testPropertyDateModified()
    {
    }

    /**
     * Test attribute "modifiedBy"
     */
    public function testPropertyModifiedBy()
    {
    }

    /**
     * Test attribute "createdBy"
     */
    public function testPropertyCreatedBy()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "modifiedByApp"
     */
    public function testPropertyModifiedByApp()
    {
    }

    /**
     * Test attribute "createdByApp"
     */
    public function testPropertyCreatedByApp()
    {
    }

    /**
     * Test attribute "interfaces"
     */
    public function testPropertyInterfaces()
    {
    }

    /**
     * Test attribute "make"
     */
    public function testPropertyMake()
    {
    }

    /**
     * Test attribute "model"
     */
    public function testPropertyModel()
    {
    }

    /**
     * Test attribute "apiVersion"
     */
    public function testPropertyApiVersion()
    {
    }

    /**
     * Test attribute "softwareVersion"
     */
    public function testPropertySoftwareVersion()
    {
    }

    /**
     * Test attribute "softwareVersionTimestamp"
     */
    public function testPropertySoftwareVersionTimestamp()
    {
    }

    /**
     * Test attribute "softwareVersionPlatform"
     */
    public function testPropertySoftwareVersionPlatform()
    {
    }

    /**
     * Test attribute "softwareVersionConfiguration"
     */
    public function testPropertySoftwareVersionConfiguration()
    {
    }

    /**
     * Test attribute "fullSoftwareVersion"
     */
    public function testPropertyFullSoftwareVersion()
    {
    }

    /**
     * Test attribute "pairingId"
     */
    public function testPropertyPairingId()
    {
    }

    /**
     * Test attribute "fingerprint"
     */
    public function testPropertyFingerprint()
    {
    }

    /**
     * Test attribute "fingerprintHint"
     */
    public function testPropertyFingerprintHint()
    {
    }

    /**
     * Test attribute "currentVersion"
     */
    public function testPropertyCurrentVersion()
    {
    }

    /**
     * Test attribute "stagedVersion"
     */
    public function testPropertyStagedVersion()
    {
    }

    /**
     * Test attribute "patch"
     */
    public function testPropertyPatch()
    {
    }

    /**
     * Test attribute "statusCode"
     */
    public function testPropertyStatusCode()
    {
    }

    /**
     * Test attribute "edgeGroup"
     */
    public function testPropertyEdgeGroup()
    {
    }

    /**
     * Test attribute "site"
     */
    public function testPropertySite()
    {
    }

    /**
     * Test attribute "softwareStatus"
     */
    public function testPropertySoftwareStatus()
    {
    }

    /**
     * Test attribute "onlineStatus"
     */
    public function testPropertyOnlineStatus()
    {
    }

    /**
     * Test attribute "serialNumber"
     */
    public function testPropertySerialNumber()
    {
    }

    /**
     * Test attribute "physicalEdge"
     */
    public function testPropertyPhysicalEdge()
    {
    }

    /**
     * Test attribute "managed"
     */
    public function testPropertyManaged()
    {
    }

    /**
     * Test attribute "edgeDeploymentType"
     */
    public function testPropertyEdgeDeploymentType()
    {
    }

    /**
     * Test attribute "callDrainingState"
     */
    public function testPropertyCallDrainingState()
    {
    }

    /**
     * Test attribute "conversationCount"
     */
    public function testPropertyConversationCount()
    {
    }

    /**
     * Test attribute "proxy"
     */
    public function testPropertyProxy()
    {
    }

    /**
     * Test attribute "offlineConfigCalled"
     */
    public function testPropertyOfflineConfigCalled()
    {
    }

    /**
     * Test attribute "osName"
     */
    public function testPropertyOsName()
    {
    }

    /**
     * Test attribute "selfUri"
     */
    public function testPropertySelfUri()
    {
    }
}
