<?php
/**
 * GKNDocumentationSearchResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  PureCloudPlatform\Client\V2
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PureCloud Platform API
 *
 * With the PureCloud Platform API, you can control all aspects of your PureCloud environment. With the APIs you can access the system configuration, manage conversations and more.
 *
 * OpenAPI spec version: v2
 * Contact: DeveloperEvangelists@genesys.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.9
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace PureCloudPlatform\Client\V2;

/**
 * GKNDocumentationSearchResponseTest Class Doc Comment
 *
 * @category    Class
 * @description GKNDocumentationSearchResponse
 * @package     PureCloudPlatform\Client\V2
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GKNDocumentationSearchResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "GKNDocumentationSearchResponse"
     */
    public function testGKNDocumentationSearchResponse()
    {
    }

    /**
     * Test attribute "total"
     */
    public function testPropertyTotal()
    {
    }

    /**
     * Test attribute "pageCount"
     */
    public function testPropertyPageCount()
    {
    }

    /**
     * Test attribute "pageSize"
     */
    public function testPropertyPageSize()
    {
    }

    /**
     * Test attribute "pageNumber"
     */
    public function testPropertyPageNumber()
    {
    }

    /**
     * Test attribute "previousPage"
     */
    public function testPropertyPreviousPage()
    {
    }

    /**
     * Test attribute "currentPage"
     */
    public function testPropertyCurrentPage()
    {
    }

    /**
     * Test attribute "nextPage"
     */
    public function testPropertyNextPage()
    {
    }

    /**
     * Test attribute "types"
     */
    public function testPropertyTypes()
    {
    }

    /**
     * Test attribute "results"
     */
    public function testPropertyResults()
    {
    }
}
