<?php
/**
 * SubscriptionOverviewUsageTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  PureCloudPlatform\Client\V2
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PureCloud Platform API
 *
 * With the PureCloud Platform API, you can control all aspects of your PureCloud environment. With the APIs you can access the system configuration, manage conversations and more.
 *
 * OpenAPI spec version: v2
 * Contact: DeveloperEvangelists@genesys.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.9
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace PureCloudPlatform\Client\V2;

/**
 * SubscriptionOverviewUsageTest Class Doc Comment
 *
 * @category    Class
 * @description SubscriptionOverviewUsage
 * @package     PureCloudPlatform\Client\V2
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SubscriptionOverviewUsageTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SubscriptionOverviewUsage"
     */
    public function testSubscriptionOverviewUsage()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "partNumber"
     */
    public function testPropertyPartNumber()
    {
    }

    /**
     * Test attribute "grouping"
     */
    public function testPropertyGrouping()
    {
    }

    /**
     * Test attribute "unitOfMeasureType"
     */
    public function testPropertyUnitOfMeasureType()
    {
    }

    /**
     * Test attribute "usageQuantity"
     */
    public function testPropertyUsageQuantity()
    {
    }

    /**
     * Test attribute "overagePrice"
     */
    public function testPropertyOveragePrice()
    {
    }

    /**
     * Test attribute "prepayQuantity"
     */
    public function testPropertyPrepayQuantity()
    {
    }

    /**
     * Test attribute "prepayPrice"
     */
    public function testPropertyPrepayPrice()
    {
    }

    /**
     * Test attribute "usageNotes"
     */
    public function testPropertyUsageNotes()
    {
    }

    /**
     * Test attribute "isCancellable"
     */
    public function testPropertyIsCancellable()
    {
    }

    /**
     * Test attribute "bundleQuantity"
     */
    public function testPropertyBundleQuantity()
    {
    }

    /**
     * Test attribute "isThirdParty"
     */
    public function testPropertyIsThirdParty()
    {
    }
}
