<?php
/**
 * SurveyAggregationQueryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  PureCloudPlatform\Client\V2
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PureCloud Platform API
 *
 * With the PureCloud Platform API, you can control all aspects of your PureCloud environment. With the APIs you can access the system configuration, manage conversations and more.
 *
 * OpenAPI spec version: v2
 * Contact: DeveloperEvangelists@genesys.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.9
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace PureCloudPlatform\Client\V2;

/**
 * SurveyAggregationQueryTest Class Doc Comment
 *
 * @category    Class
 * @description SurveyAggregationQuery
 * @package     PureCloudPlatform\Client\V2
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SurveyAggregationQueryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SurveyAggregationQuery"
     */
    public function testSurveyAggregationQuery()
    {
    }

    /**
     * Test attribute "interval"
     */
    public function testPropertyInterval()
    {
    }

    /**
     * Test attribute "granularity"
     */
    public function testPropertyGranularity()
    {
    }

    /**
     * Test attribute "timeZone"
     */
    public function testPropertyTimeZone()
    {
    }

    /**
     * Test attribute "groupBy"
     */
    public function testPropertyGroupBy()
    {
    }

    /**
     * Test attribute "filter"
     */
    public function testPropertyFilter()
    {
    }

    /**
     * Test attribute "metrics"
     */
    public function testPropertyMetrics()
    {
    }

    /**
     * Test attribute "flattenMultivaluedDimensions"
     */
    public function testPropertyFlattenMultivaluedDimensions()
    {
    }

    /**
     * Test attribute "views"
     */
    public function testPropertyViews()
    {
    }

    /**
     * Test attribute "alternateTimeDimension"
     */
    public function testPropertyAlternateTimeDimension()
    {
    }
}
