<?php
/**
 * AlertingApiTest
 * PHP version 5
 *
 * @category Class
 * @package  PureCloudPlatform\Client\V2
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PureCloud Platform API
 *
 * With the PureCloud Platform API, you can control all aspects of your PureCloud environment. With the APIs you can access the system configuration, manage conversations and more.
 *
 * OpenAPI spec version: v2
 * Contact: DeveloperEvangelists@genesys.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.9
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace PureCloudPlatform\Client\V2;

use \PureCloudPlatform\Client\V2\Configuration;
use \PureCloudPlatform\Client\V2\ApiException;
use \PureCloudPlatform\Client\V2\ObjectSerializer;

/**
 * AlertingApiTest Class Doc Comment
 *
 * @category Class
 * @package  PureCloudPlatform\Client\V2
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AlertingApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deleteAlertingInteractionstatsAlert
     *
     * Delete an interaction stats alert.
     *
     */
    public function testDeleteAlertingInteractionstatsAlert()
    {
    }

    /**
     * Test case for deleteAlertingInteractionstatsRule
     *
     * Delete an interaction stats rule..
     *
     */
    public function testDeleteAlertingInteractionstatsRule()
    {
    }

    /**
     * Test case for getAlertingAlertsActive
     *
     * Gets active alert count for a user..
     *
     */
    public function testGetAlertingAlertsActive()
    {
    }

    /**
     * Test case for getAlertingInteractionstatsAlert
     *
     * Get an interaction stats alert.
     *
     */
    public function testGetAlertingInteractionstatsAlert()
    {
    }

    /**
     * Test case for getAlertingInteractionstatsAlerts
     *
     * Get interaction stats alert list..
     *
     */
    public function testGetAlertingInteractionstatsAlerts()
    {
    }

    /**
     * Test case for getAlertingInteractionstatsAlertsUnread
     *
     * Gets user unread count of interaction stats alerts..
     *
     */
    public function testGetAlertingInteractionstatsAlertsUnread()
    {
    }

    /**
     * Test case for getAlertingInteractionstatsRule
     *
     * Get an interaction stats rule..
     *
     */
    public function testGetAlertingInteractionstatsRule()
    {
    }

    /**
     * Test case for getAlertingInteractionstatsRules
     *
     * Get an interaction stats rule list..
     *
     */
    public function testGetAlertingInteractionstatsRules()
    {
    }

    /**
     * Test case for postAlertingInteractionstatsRules
     *
     * Create an interaction stats rule..
     *
     */
    public function testPostAlertingInteractionstatsRules()
    {
    }

    /**
     * Test case for putAlertingInteractionstatsAlert
     *
     * Update an interaction stats alert read status.
     *
     */
    public function testPutAlertingInteractionstatsAlert()
    {
    }

    /**
     * Test case for putAlertingInteractionstatsRule
     *
     * Update an interaction stats rule.
     *
     */
    public function testPutAlertingInteractionstatsRule()
    {
    }
}
