<?php
/**
 * ScriptsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  PureCloudPlatform\Client\V2
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PureCloud Platform API
 *
 * With the PureCloud Platform API, you can control all aspects of your PureCloud environment. With the APIs you can access the system configuration, manage conversations and more.
 *
 * OpenAPI spec version: v2
 * Contact: DeveloperEvangelists@genesys.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.9
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace PureCloudPlatform\Client\V2;

use \PureCloudPlatform\Client\V2\Configuration;
use \PureCloudPlatform\Client\V2\ApiException;
use \PureCloudPlatform\Client\V2\ObjectSerializer;

/**
 * ScriptsApiTest Class Doc Comment
 *
 * @category Class
 * @package  PureCloudPlatform\Client\V2
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ScriptsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getScript
     *
     * Get a script.
     *
     */
    public function testGetScript()
    {
    }

    /**
     * Test case for getScriptPage
     *
     * Get a page.
     *
     */
    public function testGetScriptPage()
    {
    }

    /**
     * Test case for getScriptPages
     *
     * Get the list of pages.
     *
     */
    public function testGetScriptPages()
    {
    }

    /**
     * Test case for getScripts
     *
     * Get the list of scripts.
     *
     */
    public function testGetScripts()
    {
    }

    /**
     * Test case for getScriptsPublished
     *
     * Get the published scripts..
     *
     */
    public function testGetScriptsPublished()
    {
    }

    /**
     * Test case for getScriptsPublishedScriptId
     *
     * Get the published script..
     *
     */
    public function testGetScriptsPublishedScriptId()
    {
    }

    /**
     * Test case for getScriptsPublishedScriptIdPage
     *
     * Get the published page..
     *
     */
    public function testGetScriptsPublishedScriptIdPage()
    {
    }

    /**
     * Test case for getScriptsPublishedScriptIdPages
     *
     * Get the list of published pages.
     *
     */
    public function testGetScriptsPublishedScriptIdPages()
    {
    }

    /**
     * Test case for getScriptsPublishedScriptIdVariables
     *
     * Get the published variables.
     *
     */
    public function testGetScriptsPublishedScriptIdVariables()
    {
    }

    /**
     * Test case for getScriptsUploadStatus
     *
     * Get the upload status of an imported script.
     *
     */
    public function testGetScriptsUploadStatus()
    {
    }

    /**
     * Test case for postScriptExport
     *
     * Export a script via download service..
     *
     */
    public function testPostScriptExport()
    {
    }
}
